### ISSUE TITLE
public/private keys vs site/secret keys

### ISSUE THREAD

**Issue by crhallberg** [Lansoweb/LosReCaptcha#1]
The [Google reCAPTCHA documents](https://developers.google.com/recaptcha/docs/start) refer to the private and public keys as the secret and site keys now, respectively.

Just wanted to know your thoughts on changing the code to reflect that or is private/public going to be more backwards compatible or beneficial in another way.

**Comment by Lansoweb** [comment]
You're right. I kept the names to have minimum change on the client side, but will create the proper names and the "old ones" will become alias.

**Comment by Lansoweb** [comment]
@crhallberg Hi! Just updated to 0.9.1 with the new key names, but kept the old ones for BC and minimum change in the configs/code from old->new migrations
