### ISSUE TITLE
Impossibe to set language

### ISSUE THREAD

**Issue by waltertamboer** [Lansoweb/LosReCaptcha#3]
There is a small bug and I'm not entirely sure if it's part of this library or that the bug is in zendframework/zend-captcha.

The default language is set to null [as can be seen here](https://github.com/Lansoweb/LosReCaptcha/blob/master/src/LosReCaptcha/Service/ReCaptcha.php#L90). Because there is an isset check around the option, the option will never get set. See [this link](https://github.com/zendframework/zend-captcha/blob/master/src/ReCaptcha.php#L178)

**Comment by Lansoweb** [comment]
@waltertamboer You are right. Just opened a PR for ZF team: https://github.com/zendframework/zend-captcha/pull/6. Thanks!

**Comment by Lansoweb** [comment]
Closing this. The above PR was already merged. Thanks.
