### ISSUE TITLE
ZF3 options

### ISSUE THREAD

**Issue by robob4him** [Lansoweb/LosReCaptcha#5]
Are you planning on supporting ZF3?

**Comment by Lansoweb** [comment]
Hi! Sure, I'm refatoring most of my libs to support ZF3 / PSR-7. Probably will finish this one this weekend.

**Comment by Lansoweb** [comment]
@robob4him Hi! Just release a 2.0 version. Added to a project with Zend Expressive and Zend\Form, and worked without a problem, not tested with ZF3 but should work. Could you give it a try? Thanks!

**Comment by robob4him** [comment]
@Lansoweb, It works until it attempts to render the captcha. I get this notice:
Notice: Undefined index: theme in /var/www/mygsslink-devf/vendor/los/losrecaptcha/src/Service/ReCaptcha.php on line 143

It appears to occur because Service\ReCaptcha's __construct always overwrites the instance options with $options parameter (which defaults to an empty array) and Captcha\ReCaptcha creates the service with only the first two parameters. So when it is rendered $this->options is empty.

Perhaps it could be changed to 

``` php
$this->options = $options + $this->options;
```

to preserve the defaults?

Thanks for your work! Very close!

**Comment by Lansoweb** [comment]
Hello @robob4him, thanks  again. Just fixed and created a new release with the fix: https://github.com/Lansoweb/LosReCaptcha/releases/tag/2.0.1.

**Comment by robob4him** [comment]
Works great! Thanks, @Lansoweb!
